// AUTO-GENERATED by tools/fetch_tiles.py -- do not hand-edit.
// Copyright 2025-2026 David M. King
// SPDX-License-Identifier: Apache-2.0

#pragma once
#include <stdint.h>

typedef struct {
    int32_t zoom;
    int32_t base_tx, base_ty;
    int32_t cols, rows;
    uint32_t tile_index_start; // index (not byte offset) of this level's first tile
} embedded_zoom_t;

static const embedded_zoom_t MAP_EMBEDDED_ZOOMS[] = {
    { 10, 231, 407, 8, 10, 0 },
    { 11, 466, 820, 8, 10, 80 },
    { 12, 936, 1646, 8, 10, 160 },
    { 13, 1876, 3297, 8, 10, 240 },
    { 14, 3757, 6600, 8, 10, 320 },
    { 15, 7519, 13205, 8, 10, 400 },
    { 16, 15043, 26416, 8, 10, 480 },
    { 17, 30091, 52838, 8, 10, 560 },
    { 18, 60186, 105682, 8, 10, 640 },
    { 19, 120376, 211369, 8, 10, 720 },
};
#define MAP_EMBEDDED_ZOOM_COUNT ((int)(sizeof(MAP_EMBEDDED_ZOOMS) / sizeof(MAP_EMBEDDED_ZOOMS[0])))
